export const PRODUCT_IMAGE_URLS = {
  iphone16Pro: "https://cdn2.cellphones.com.vn/insecure/plain/https%3A/cellphones.com.vn/media/catalog/product/i/p/iphone-16-pro-max.png",
  iphone16: "https://pngimg.com/uploads/iphone16/iphone16_PNG6.png",
  s25Ultra: "https://cadenamulti.co/cdn/shop/files/Diseno_sin_titulo_48_00bc1279-4d6e-4326-9429-e7b084a1b5f4.png?v=1737591859&width=2048",
  iphone15Plus: "https://toppng.com/uploads/preview/hd-apple-iphone-15-plus-blue-front-and-back-view-png-image-11695041100rehlukffig.png",
  s24Fe: "https://cdn.beebom.com/mobile/2024/03/Samsung-GalaxyS24-FE.png",
};

export const defaultProducts = [
  {
    id: "p1",
    name: "iPhone 16 Pro Max",
    category: "iPhone",
    price: 30990000,
    oldPrice: 34990000,
    image: PRODUCT_IMAGE_URLS.iphone16Pro,
    images: [PRODUCT_IMAGE_URLS.iphone16Pro, PRODUCT_IMAGE_URLS.iphone16, PRODUCT_IMAGE_URLS.iphone15Plus, PRODUCT_IMAGE_URLS.iphone16Pro],
    description: "Thiết kế titanium cao cấp, camera chuyên nghiệp và thời lượng pin bền bỉ cho cả ngày dài.",
    screen: "6.9 inch Super Retina XDR",
    camera: "Fusion 48MP",
    chip: "Apple A18 Pro",
    storage: "256GB",
    stock: 18,
    badge: "Bán chạy",
  },
  {
    id: "p2",
    name: "Galaxy S25 Ultra",
    category: "Samsung",
    price: 28990000,
    oldPrice: 33990000,
    image: PRODUCT_IMAGE_URLS.s25Ultra,
    images: [PRODUCT_IMAGE_URLS.s25Ultra, PRODUCT_IMAGE_URLS.s24Fe, PRODUCT_IMAGE_URLS.s25Ultra, PRODUCT_IMAGE_URLS.s24Fe],
    description: "Trợ lý Galaxy AI, bút S Pen tích hợp và hệ thống camera zoom linh hoạt.",
    screen: "6.9 inch Dynamic AMOLED 2X",
    camera: "200MP",
    chip: "Snapdragon 8 Elite",
    storage: "256GB",
    stock: 12,
    badge: "Mới",
  },
  {
    id: "p3",
    name: "iPhone 16",
    category: "iPhone",
    price: 21990000,
    oldPrice: 24990000,
    image: PRODUCT_IMAGE_URLS.iphone16,
    images: [PRODUCT_IMAGE_URLS.iphone16, PRODUCT_IMAGE_URLS.iphone16Pro, PRODUCT_IMAGE_URLS.iphone15Plus, PRODUCT_IMAGE_URLS.iphone16],
    description: "Nhỏ gọn, mạnh mẽ với chip A18 và nút Camera Control tiện dụng.",
    screen: "6.1 inch Super Retina XDR",
    camera: "Fusion 48MP",
    chip: "Apple A18",
    storage: "128GB",
    stock: 24,
    badge: "",
  },
  {
    id: "p4",
    name: "Galaxy Z Flip6",
    category: "Samsung",
    price: 19990000,
    oldPrice: 26990000,
    image: PRODUCT_IMAGE_URLS.s24Fe,
    images: [PRODUCT_IMAGE_URLS.s24Fe, PRODUCT_IMAGE_URLS.s25Ultra, PRODUCT_IMAGE_URLS.s24Fe, PRODUCT_IMAGE_URLS.s25Ultra],
    description: "Thiết kế gập thời trang, màn hình phụ tiện lợi và camera tối ưu bằng AI.",
    screen: "6.7 inch Dynamic AMOLED 2X",
    camera: "50MP",
    chip: "Snapdragon 8 Gen 3",
    storage: "256GB",
    stock: 9,
    badge: "Giảm sâu",
  },
  {
    id: "p5",
    name: "iPhone 15 Plus",
    category: "iPhone",
    price: 18990000,
    oldPrice: 22990000,
    image: PRODUCT_IMAGE_URLS.iphone15Plus,
    images: [PRODUCT_IMAGE_URLS.iphone15Plus, PRODUCT_IMAGE_URLS.iphone16, PRODUCT_IMAGE_URLS.iphone15Plus, PRODUCT_IMAGE_URLS.iphone16Pro],
    description: "Màn hình lớn, pin lâu và Dynamic Island trong một thiết kế trẻ trung.",
    screen: "6.7 inch Super Retina XDR",
    camera: "48MP",
    chip: "Apple A16 Bionic",
    storage: "128GB",
    stock: 15,
    badge: "",
  },
  {
    id: "p6",
    name: "Galaxy S24 FE",
    category: "Samsung",
    price: 12990000,
    oldPrice: 16990000,
    image: PRODUCT_IMAGE_URLS.s24Fe,
    images: [PRODUCT_IMAGE_URLS.s24Fe, PRODUCT_IMAGE_URLS.s25Ultra, PRODUCT_IMAGE_URLS.s24Fe, PRODUCT_IMAGE_URLS.s25Ultra],
    description: "Trải nghiệm Galaxy AI dễ tiếp cận với màn hình AMOLED sáng đẹp.",
    screen: "6.7 inch Dynamic AMOLED 2X",
    camera: "50MP",
    chip: "Exynos 2400e",
    storage: "256GB",
    stock: 21,
    badge: "Giá tốt",
  },
];

export const defaultStores = [
  { id: "s1", name: "TIN STUDIO Thủ Đức", address: "Võ Văn Ngân, TP. Thủ Đức, TP.HCM", hours: "08:00 - 21:30", phone: "028 7300 1998" },
  { id: "s2", name: "TIN STUDIO Quận 1", address: "Nguyễn Thị Minh Khai, Quận 1, TP.HCM", hours: "08:00 - 22:00", phone: "028 7300 2998" },
  { id: "s3", name: "TIN STUDIO Bình Thạnh", address: "Xô Viết Nghệ Tĩnh, Bình Thạnh, TP.HCM", hours: "08:30 - 21:30", phone: "028 7300 3998" },
];
